kaminariによるページング機能の実装
pepabo-college/sunecosuri-todo-app pull request #5
Opened 2017-06-06 08:46 UTC by sunecosuri

##　概要
gemのkaminariを用いてページング機能を実装しました。
5件ごとにページングをするよう/app/models/task.rbに設定しています。

Modelの記述箇所はkaminariの［README.md](https://github.com/kaminari/kaminari#user-content-controllers)を参考にしました。

## 確認いただきたいところ
そんなにファイルを編集せずにすんなりページングがうまく言ったので驚いたのですが、
設定漏れやこうした方がスマートなどないかご確認いただければと思います。

## レビュアー
@udzura @bake0937 @sunecosuri (敬称略)

2017-06-06 08:48 UTC, udzura commented on app/views/tasks/index.html.erb
> +<!--  -->
なぜ、上下にコメントが...

2017-06-06 08:49 UTC, udzura commented
ちなみに

* 表示は確認しましたか？
* どういう手順で確認しましたか？(シードデータの作り方など)

2017-06-06 08:51 UTC, sunecosuri commented on app/views/tasks/index.html.erb
> +<!--  -->
コメントの追加漏れでした。追記して再コミットします。

2017-06-06 08:57 UTC, sunecosuri commented
シードデータ作らずに手動でやって表示を確認していたので、出来次第コミットします。

2017-06-06 09:44 UTC, sunecosuri commented
シードデータ作成して以下の手順で確認しました。
```
rake db:seed
rails s
```

2017-06-06 09:46 UTC, udzura requested changes

2017-06-06 09:46 UTC, udzura commented on db/seeds.rb
> +    content:    "test-content#{index}",
良いですね 👍 
気になったのは

* id: は明示しない方がいい（seed以外で作ったデータなどがあって、idがかぶると更新できない）
* ちょっとスペースの開け方が変

2017-06-07 00:51 UTC, bake0937 commented
Viewの修正をするプルリクの内容にスクリーンショットを載せるとレビュアーはレビューがやりやすいという話を思い出しました。
(私も今プルリク修正しました。)

2017-06-07 01:17 UTC, bake0937 commented on db/seeds.rb
> +    content:    "test-content#{index}",
>ちょっとスペースの開け方が変
rubocop-auto-correctを入れるとファイル保存時に変なインデントを直してくれるそうです。
[方法]
1.  rubocupを入れる
```gem install rubocop```
1. Atomのアドオンrubocop-auto-correctを入れる(設定は公式参照)
[公式](https://atom.io/packages/rubocop-auto-correct)
※もし、rubocopが実行されない場合はAtomでコマンドパレット(cmd+shift+p)を開いて、「RUbocop Auto Correct: Toggle Auto Run」を選択し、実行する

2017-06-07 05:41 UTC, udzura commented
> kaminari-bootstrapを入れる

今後の課題になりました！

2017-06-07 05:42 UTC, udzura approved these changes

2017-06-07 05:42 UTC, merged